[project]
name = "ukaiforum-inspect-workshop"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "inspect_ai==0.3.146",
    "inspect_wandb[weave]==0.2.0",
    "inspect_evals==0.3.102",
]
